# Sử dụng image gốc
FROM bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8

USER root

RUN sed -i 's/deb.debian.org/archive.debian.org/g' /etc/apt/sources.list
RUN sed -i 's/security.debian.org/archive.debian.org/g' /etc/apt/sources.list
RUN sed -i '/stretch-updates/d' /etc/apt/sources.list

RUN apt-get update && apt-get install -y python3